name: Check tag files

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  tags:
    runs-on: ubuntu-latest

    name: Check tag files
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: 3.4.8
          bundler-cache: true
      - name: Check tag files are properly updated
        run: |
          bundle exec rake update_tags
          git --no-pager diff --exit-code
