name: Check tag files

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  tags:
    runs-on: ubuntu-latest

    name: Check tag files
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          ruby-version: 3.4.8
          bundler-cache: true
      - name: Check tag files are properly updated
        run: |
          bundle exec rake update_tags
          git --no-pager diff --exit-code
